### ISSUE TITLE
Document synthesised `keypress` events

### ISSUE THREAD

**Issue by jalbam** [cvan/gamepad-plus#65]
Hello,

I have reading the source code of the example and it seems you are using a property called "keyEventsEnabled". What is this for? The documentation does not talk about it.

Thank you very much in advance.

Cheers,
 Joan

**Comment by cvan** [comment]
That's to emulate `keypress` events so you don't have to have access to a physical gamepad; you can use your keyboard.

Yeah, sorry about that; the docs are basically non-existent. When we have time, we will update the docs, or if anyone else wants to, we'd appreciate any help. Thank you!

**Comment by jalbam** [comment]
Thank you very much for your reply.

I think I understand now. First, I thought it was for some platforms that fire keyboard events in their browser when the gamepad is used (as for example Nintendo DSi, Nintendo Wii, many SmartTV's, etc.). But this seems different. Correct me if I am wrong, please.

**Comment by cvan** [comment]
Yeah, that's correct. I'll keep this issue open (I've retitled the issue so it's properly tracked). Thanks for filing! And, let me know if you have any additional issues.

**Comment by jalbam** [comment]
Thank you very much for all. Maybe I could do the complete documentation if you want but I would need some more information to create it.

**Comment by cvan** [comment]
Thanks for the offer 😄  By no means should you feel obligated, but feel free to open a PR any time.

**Comment by jalbam** [comment]
That is ok. I will do it if I find some time. Thank you very much. See you!
